import { APP_CONFIG } from "@/constants/config";
import type { ModelConfig, TopUpPack } from "@/types";

export const MODELS: ModelConfig[] = [
  {
    id: "qwen/qwen3-coder:free",
    displayName: "Qwen3 Coder",
    provider: "Alibaba",
    modality: "text",
    supportsReasoning: false,
    isFree: true,
    inputCostPerMToken: 0,
    outputCostPerMToken: 0,
    contextWindow: 262000,
    maxOutput: 262000,
    description: "Free. Good for onboarding and quick tasks.",
  },
  {
    id: "z-ai/glm-5.1",
    displayName: "GLM-5.1",
    provider: "Zhipu AI",
    modality: "text",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.98,
    outputCostPerMToken: 3.08,
    contextWindow: 202752,
    maxOutput: 202752,
    description: "Structured presentation. Best for formal documents, slide outlines, and JSON artifacts.",
  },
  {
    id: "qwen/qwen3.6-plus",
    displayName: "Qwen3.6 Plus",
    provider: "Alibaba",
    modality: "text+image+video",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.325,
    outputCostPerMToken: 1.95,
    contextWindow: 1000000,
    maxOutput: 65536,
    description: "Conversational tutoring with vision. Patient, explains concepts clearly, great for learning.",
  },
  {
    id: "deepseek/deepseek-v3.2",
    displayName: "DeepSeek V3.2",
    provider: "DeepSeek",
    modality: "text",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.252,
    outputCostPerMToken: 0.378,
    contextWindow: 131072,
    maxOutput: 65536,
    description: "Deep analytical reasoning. Best for code review, logic problems, and multi-step analysis.",
  },
  {
    id: "mistralai/mistral-small-2603",
    displayName: "Mistral Small",
    provider: "Mistral AI",
    modality: "text+image",
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.15,
    outputCostPerMToken: 0.6,
    contextWindow: 262144,
    maxOutput: 262144,
    description: "Creative ideation with vision. Best for brainstorming, writing, and content generation.",
  },
  {
    id: "moonshotai/kimi-k2.5",
    displayName: "Kimi K2.5",
    provider: "Moonshot AI",
    modality: "text+image",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.4,
    outputCostPerMToken: 1.9,
    contextWindow: 262144,
    maxOutput: 262144,
    description: "Long context analysis with vision. Best for large documents, images, and conversation recall.",
  },
  {
    id: "google/gemini-2.5-flash-lite",
    displayName: "Gemini Flash Lite",
    provider: "Google",
    modality: "text+image+file+audio+video",
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.1,
    outputCostPerMToken: 0.4,
    contextWindow: 1048576,
    maxOutput: 65535,
    description: "OCR, document parsing, images, audio. Extracts text from any format.",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct:free",
    displayName: "Qwen3 Next",
    provider: "Alibaba",
    modality: "text",
    supportsReasoning: true,
    isFree: true,
    inputCostPerMToken: 0,
    outputCostPerMToken: 0,
    contextWindow: 262144,
    maxOutput: 65536,
    description: "Bilingual reasoning. Strong across Chinese and English, free.",
  },
];

export const FREE_MODEL_ID = "qwen/qwen3-coder:free";
export const DEFAULT_MODEL_ID = FREE_MODEL_ID;

export const TOP_UP_PACKS: TopUpPack[] = [
  { id: "pkg_100", label: "Starter", amountInr: 100, creditsInr: 100, bonusLabel: "—" },
  { id: "pkg_250", label: "Popular", amountInr: 250, creditsInr: 262, bonusLabel: "+5%" },
  { id: "pkg_500", label: "Value", amountInr: 500, creditsInr: 535, bonusLabel: "+7%" },
  { id: "pkg_1000", label: "Pro", amountInr: 1000, creditsInr: 1100, bonusLabel: "+10%" },
];

export const FRONTIER_BASELINE = {
  id: APP_CONFIG.frontierBaselineModel,
  displayName: "Claude 3.5 Sonnet",
  inputCostPerMToken: 3,
  outputCostPerMToken: 15,
};
