export const GLOBAL_MARKUP = 1.4;
export const USD_TO_INR = 83.5;
export const FRONTIER_BASELINE = {
  id: "anthropic/claude-3.5-sonnet",
  inputCostPerMToken: 3,
  outputCostPerMToken: 15,
};

export const CURATED_MODELS = [
  {
    id: "deepseek/deepseek-v4-flash:free",
    displayName: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    role: "free",
    modality: "text",
    supportsReasoning: false,
    isFree: true,
    inputCostPerMToken: 0,
    outputCostPerMToken: 0,
    contextWindow: 163840,
    maxOutput: 16384,
    description: "Free. Good for onboarding and quick tasks.",
  },
  {
    id: "z-ai/glm-5.1",
    displayName: "GLM-5.1",
    provider: "Zhipu AI",
    role: "structured",
    modality: "text",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.98,
    outputCostPerMToken: 3.08,
    contextWindow: 202752,
    maxOutput: 65536,
    description: "Structured presentation. Best for formal documents, slide outlines, and JSON artifacts.",
  },
  {
    id: "qwen/qwen3.6-plus",
    displayName: "Qwen3.6 Plus",
    provider: "Alibaba",
    role: "tutoring",
    modality: "text+image+video",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.325,
    outputCostPerMToken: 1.95,
    contextWindow: 1000000,
    maxOutput: 65536,
    description: "Conversational tutoring with vision. Patient, explains concepts clearly, great for learning.",
  },
  {
    id: "deepseek/deepseek-v3.2",
    displayName: "DeepSeek V3.2",
    provider: "DeepSeek",
    role: "reasoning",
    modality: "text",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.252,
    outputCostPerMToken: 0.378,
    contextWindow: 131072,
    maxOutput: 65536,
    description: "Deep analytical reasoning. Best for code review, logic problems, and multi-step analysis.",
  },
  {
    id: "mistralai/mistral-small-2603",
    displayName: "Mistral Small",
    provider: "Mistral AI",
    role: "creative",
    modality: "text+image",
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.15,
    outputCostPerMToken: 0.6,
    contextWindow: 262144,
    maxOutput: 65536,
    description: "Creative ideation with vision. Best for brainstorming, writing, and content generation.",
  },
  {
    id: "moonshotai/kimi-k2.5",
    displayName: "Kimi K2.5",
    provider: "Moonshot AI",
    role: "context",
    modality: "text+image",
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.4,
    outputCostPerMToken: 1.9,
    contextWindow: 262144,
    maxOutput: 65536,
    description: "Long context analysis with vision. Best for large documents, images, and conversation recall.",
  },
  {
    id: "google/gemini-2.5-flash-lite",
    displayName: "Gemini Flash Lite",
    provider: "Google",
    role: "ocr",
    modality: "text+image+file+audio+video",
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.1,
    outputCostPerMToken: 0.4,
    contextWindow: 1048576,
    maxOutput: 65535,
    description: "OCR, document parsing, images, audio. Extracts text from any format.",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct:free",
    displayName: "Qwen3 Next",
    provider: "Alibaba",
    role: "bilingual",
    modality: "text",
    supportsReasoning: true,
    isFree: true,
    inputCostPerMToken: 0,
    outputCostPerMToken: 0,
    contextWindow: 262144,
    maxOutput: 65536,
    description: "Bilingual reasoning. Strong across Chinese and English, free.",
  },
];

export const TOP_UP_PACKS = {
  pkg_100: { amountInr: 100, creditsInr: 100, label: "Starter" },
  pkg_250: { amountInr: 250, creditsInr: 262, label: "Popular" },
  pkg_500: { amountInr: 500, creditsInr: 535, label: "Value" },
  pkg_1000: { amountInr: 1000, creditsInr: 1100, label: "Pro" },
} as const;
