export const GLOBAL_MARKUP = 1.4;
export const USD_TO_INR = 83.5;
export const FRONTIER_BASELINE = {
  id: "anthropic/claude-3.5-sonnet",
  inputCostPerMToken: 3,
  outputCostPerMToken: 15,
};

export const CURATED_MODELS = [
  {
    id: "google/gemini-2.5-flash-lite",
    displayName: "Gemini 2.5 Flash Lite",
    provider: "Google",
    supportsVision: true,
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.1,
    outputCostPerMToken: 0.4,
    contextWindow: 1000000,
    maxOutput: 64000,
    description: "Fast and cheap. Best for everyday conversation.",
  },
  {
    id: "qwen/qwen3-coder:free",
    displayName: "Qwen3 Coder",
    provider: "Alibaba",
    supportsVision: false,
    supportsReasoning: false,
    isFree: true,
    inputCostPerMToken: 0,
    outputCostPerMToken: 0,
    contextWindow: 262000,
    maxOutput: 8192,
    description: "Free model. Great for onboarding and lightweight tasks.",
  },
  {
    id: "minimax/minimax-m2.7",
    displayName: "MiniMax Fast",
    provider: "MiniMax",
    supportsVision: true,
    supportsReasoning: false,
    isFree: false,
    inputCostPerMToken: 0.3,
    outputCostPerMToken: 1.1,
    contextWindow: 1000000,
    maxOutput: 8192,
    description: "Fast and cheap. Best for everyday conversation.",
  },
  {
    id: "deepseek/deepseek-v3.2",
    displayName: "DeepSeek Smart",
    provider: "DeepSeek",
    supportsVision: false,
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.35,
    outputCostPerMToken: 1.4,
    contextWindow: 131072,
    maxOutput: 16384,
    description: "Default paid model. Strong reasoning, great value.",
  },
  {
    id: "qwen/qwen3-6-plus",
    displayName: "Qwen Plus",
    provider: "Alibaba",
    supportsVision: true,
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 0.5,
    outputCostPerMToken: 2,
    contextWindow: 131072,
    maxOutput: 16384,
    description: "Balanced. Handles images and complex tasks well.",
  },
  {
    id: "zai-org/glm-5.1",
    displayName: "GLM-5.1 Frontier",
    provider: "Zhipu AI",
    supportsVision: true,
    supportsReasoning: true,
    isFree: false,
    inputCostPerMToken: 1.05,
    outputCostPerMToken: 4.2,
    contextWindow: 200000,
    maxOutput: 128000,
    description: "Frontier quality. Competes with Claude Opus on coding.",
  },
];

export const TOP_UP_PACKS = {
  pkg_100: { amountInr: 100, creditsInr: 100, label: "Starter" },
  pkg_250: { amountInr: 250, creditsInr: 262, label: "Popular" },
  pkg_500: { amountInr: 500, creditsInr: 535, label: "Value" },
  pkg_1000: { amountInr: 1000, creditsInr: 1100, label: "Pro" },
} as const;

